# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: buyer.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import market_pb2 as market__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x62uyer.proto\x1a\x0cmarket.proto\"\x90\x01\n\x04Item\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x03 \x01(\t\x12\x10\n\x08quantity\x18\x04 \x01(\x05\x12\x13\n\x0b\x64\x65scription\x18\x05 \x01(\t\x12\r\n\x05price\x18\x06 \x01(\x02\x12\x0e\n\x06rating\x18\x07 \x01(\x02\x12\x16\n\x0eseller_address\x18\x08 \x01(\t\"8\n\x11SearchItemRequest\x12\x11\n\titem_name\x18\x01 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x02 \x01(\t\"*\n\x12SearchItemResponse\x12\x14\n\x05items\x18\x01 \x03(\x0b\x32\x05.Item\"J\n\x0e\x42uyItemRequest\x12\x0f\n\x07item_id\x18\x01 \x01(\x05\x12\x10\n\x08quantity\x18\x02 \x01(\x05\x12\x15\n\rbuyer_address\x18\x03 \x01(\t\"!\n\x0f\x42uyItemResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\">\n\x14\x41\x64\x64ToWishListRequest\x12\x0f\n\x07item_id\x18\x01 \x01(\x05\x12\x15\n\rbuyer_address\x18\x02 \x01(\t\"8\n\x15\x41\x64\x64ToWishListResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"I\n\x0fRateItemRequest\x12\x0f\n\x07item_id\x18\x01 \x01(\x05\x12\x15\n\rbuyer_address\x18\x02 \x01(\t\x12\x0e\n\x06rating\x18\x03 \x01(\x02\"3\n\x10RateItemResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t2\xec\x01\n\x0c\x42uyerService\x12\x37\n\nSearchItem\x12\x12.SearchItemRequest\x1a\x13.SearchItemResponse\"\x00\x12.\n\x07\x42uyItem\x12\x0f.BuyItemRequest\x1a\x10.BuyItemResponse\"\x00\x12@\n\rAddToWishList\x12\x15.AddToWishListRequest\x1a\x16.AddToWishListResponse\"\x00\x12\x31\n\x08RateItem\x12\x10.RateItemRequest\x1a\x11.RateItemResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'buyer_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ITEM']._serialized_start=30
  _globals['_ITEM']._serialized_end=174
  _globals['_SEARCHITEMREQUEST']._serialized_start=176
  _globals['_SEARCHITEMREQUEST']._serialized_end=232
  _globals['_SEARCHITEMRESPONSE']._serialized_start=234
  _globals['_SEARCHITEMRESPONSE']._serialized_end=276
  _globals['_BUYITEMREQUEST']._serialized_start=278
  _globals['_BUYITEMREQUEST']._serialized_end=352
  _globals['_BUYITEMRESPONSE']._serialized_start=354
  _globals['_BUYITEMRESPONSE']._serialized_end=387
  _globals['_ADDTOWISHLISTREQUEST']._serialized_start=389
  _globals['_ADDTOWISHLISTREQUEST']._serialized_end=451
  _globals['_ADDTOWISHLISTRESPONSE']._serialized_start=453
  _globals['_ADDTOWISHLISTRESPONSE']._serialized_end=509
  _globals['_RATEITEMREQUEST']._serialized_start=511
  _globals['_RATEITEMREQUEST']._serialized_end=584
  _globals['_RATEITEMRESPONSE']._serialized_start=586
  _globals['_RATEITEMRESPONSE']._serialized_end=637
  _globals['_BUYERSERVICE']._serialized_start=640
  _globals['_BUYERSERVICE']._serialized_end=876
# @@protoc_insertion_point(module_scope)
