# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: market.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cmarket.proto\"6\n\x15RegisterSellerRequest\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\x12\x0c\n\x04uuid\x18\x02 \x01(\t\"(\n\x16RegisterSellerResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"3\n\x13NotifyClientRequest\x12\x1c\n\x14notification_message\x18\x01 \x01(\t\"&\n\x14NotifyClientResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2\x93\x01\n\rMarketService\x12\x43\n\x0eRegisterSeller\x12\x16.RegisterSellerRequest\x1a\x17.RegisterSellerResponse\"\x00\x12=\n\x0cNotifyClient\x12\x14.NotifyClientRequest\x1a\x15.NotifyClientResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'market_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_REGISTERSELLERREQUEST']._serialized_start=16
  _globals['_REGISTERSELLERREQUEST']._serialized_end=70
  _globals['_REGISTERSELLERRESPONSE']._serialized_start=72
  _globals['_REGISTERSELLERRESPONSE']._serialized_end=112
  _globals['_NOTIFYCLIENTREQUEST']._serialized_start=114
  _globals['_NOTIFYCLIENTREQUEST']._serialized_end=165
  _globals['_NOTIFYCLIENTRESPONSE']._serialized_start=167
  _globals['_NOTIFYCLIENTRESPONSE']._serialized_end=205
  _globals['_MARKETSERVICE']._serialized_start=208
  _globals['_MARKETSERVICE']._serialized_end=355
# @@protoc_insertion_point(module_scope)
