# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: market.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cmarket.proto\"3\n\x13NotifyClientRequest\x12\x1c\n\x14notification_message\x18\x01 \x01(\t\"g\n\x14NotifyClientResponse\x12,\n\x06status\x18\x01 \x01(\x0e\x32\x1c.NotifyClientResponse.Status\"!\n\x06Status\x12\x0b\n\x07SUCCESS\x10\x00\x12\n\n\x06\x46\x41ILED\x10\x01\x32N\n\rMarketService\x12=\n\x0cNotifyClient\x12\x14.NotifyClientRequest\x1a\x15.NotifyClientResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'market_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_NOTIFYCLIENTREQUEST']._serialized_start=16
  _globals['_NOTIFYCLIENTREQUEST']._serialized_end=67
  _globals['_NOTIFYCLIENTRESPONSE']._serialized_start=69
  _globals['_NOTIFYCLIENTRESPONSE']._serialized_end=172
  _globals['_NOTIFYCLIENTRESPONSE_STATUS']._serialized_start=139
  _globals['_NOTIFYCLIENTRESPONSE_STATUS']._serialized_end=172
  _globals['_MARKETSERVICE']._serialized_start=174
  _globals['_MARKETSERVICE']._serialized_end=252
# @@protoc_insertion_point(module_scope)
