# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: seller.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import market_pb2 as market__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cseller.proto\x1a\x0cmarket.proto\"\x8d\x01\n\x0fSellItemRequest\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x03 \x01(\t\x12\x10\n\x08quantity\x18\x04 \x01(\x05\x12\x13\n\x0b\x64\x65scription\x18\x05 \x01(\t\x12\x16\n\x0eseller_address\x18\x06 \x01(\t\x12\r\n\x05price\x18\x07 \x01(\x02\"3\n\x10SellItemResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07item_id\x18\x02 \x01(\x05\"S\n\x11UpdateItemRequest\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x0f\n\x07item_id\x18\x02 \x01(\x05\x12\r\n\x05price\x18\x03 \x01(\x02\x12\x10\n\x08quantity\x18\x04 \x01(\x05\"$\n\x12UpdateItemResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"9\n\x11\x44\x65leteItemRequest\x12\x13\n\x0bseller_uuid\x18\x01 \x01(\t\x12\x0f\n\x07item_id\x18\x02 \x01(\x05\"$\n\x12\x44\x65leteItemResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\":\n\x19\x44isplaySellerItemsRequest\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\x12\x0c\n\x04uuid\x18\x02 \x01(\t\"6\n\x1a\x44isplaySellerItemsResponse\x12\x18\n\x05items\x18\x01 \x03(\x0b\x32\t.ItemInfo\"\x94\x01\n\x08ItemInfo\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x03 \x01(\t\x12\x10\n\x08quantity\x18\x04 \x01(\x05\x12\x13\n\x0b\x64\x65scription\x18\x05 \x01(\t\x12\x16\n\x0eseller_address\x18\x06 \x01(\t\x12\r\n\x05price\x18\x07 \x01(\x02\x12\x0e\n\x06rating\x18\x08 \x01(\x02\x32\xca\x02\n\rSellerService\x12\x43\n\x0eRegisterSeller\x12\x16.RegisterSellerRequest\x1a\x17.RegisterSellerResponse\"\x00\x12\x31\n\x08SellItem\x12\x10.SellItemRequest\x1a\x11.SellItemResponse\"\x00\x12\x37\n\nUpdateItem\x12\x12.UpdateItemRequest\x1a\x13.UpdateItemResponse\"\x00\x12\x37\n\nDeleteItem\x12\x12.DeleteItemRequest\x1a\x13.DeleteItemResponse\"\x00\x12O\n\x12\x44isplaySellerItems\x12\x1a.DisplaySellerItemsRequest\x1a\x1b.DisplaySellerItemsResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'seller_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SELLITEMREQUEST']._serialized_start=31
  _globals['_SELLITEMREQUEST']._serialized_end=172
  _globals['_SELLITEMRESPONSE']._serialized_start=174
  _globals['_SELLITEMRESPONSE']._serialized_end=225
  _globals['_UPDATEITEMREQUEST']._serialized_start=227
  _globals['_UPDATEITEMREQUEST']._serialized_end=310
  _globals['_UPDATEITEMRESPONSE']._serialized_start=312
  _globals['_UPDATEITEMRESPONSE']._serialized_end=348
  _globals['_DELETEITEMREQUEST']._serialized_start=350
  _globals['_DELETEITEMREQUEST']._serialized_end=407
  _globals['_DELETEITEMRESPONSE']._serialized_start=409
  _globals['_DELETEITEMRESPONSE']._serialized_end=445
  _globals['_DISPLAYSELLERITEMSREQUEST']._serialized_start=447
  _globals['_DISPLAYSELLERITEMSREQUEST']._serialized_end=505
  _globals['_DISPLAYSELLERITEMSRESPONSE']._serialized_start=507
  _globals['_DISPLAYSELLERITEMSRESPONSE']._serialized_end=561
  _globals['_ITEMINFO']._serialized_start=564
  _globals['_ITEMINFO']._serialized_end=712
  _globals['_SELLERSERVICE']._serialized_start=715
  _globals['_SELLERSERVICE']._serialized_end=1045
# @@protoc_insertion_point(module_scope)
